# Generated by Django 5.2.3 on 2025-06-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='descrption',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
