# Generated by Django 5.2.3 on 2025-06-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_remove_sitesetup_descrption_sitesetup_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
    ]
